#define _ANDROID
#define OUTLINES

uniform sampler2D Texture0;

uniform float4 UserPSHParams[ 1 ];

float4 main(
	float2 uv0Varying : TEXCOORD0,
	float4 colorVarying : COLOR
) {
	float4 color=colorVarying;
	float4 txt=tex2D(Texture0,uv0Varying.xy);
	
#ifdef OUTLINES
	float4 fontColor 	= colorVarying;
	float4 outlineColor 	= UserPSHParams[ 0 ];

	color	= lerp( outlineColor, fontColor, txt.x );
	color.w	*= txt.x + txt.w;
#else
	color.w *= txt.w;
#endif	

	return color;
}
